Proiect_DAW-DeliANN/Models/Channel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Proiect_DAW_DeliANN.Models
{
    public class Channel
    {
        [Key]
        public int ChannelId { get; set; }

        [Required(ErrorMessage = "Chanel Name is required")]
        [StringLength(200, ErrorMessage = "Channel Name must have at most 200 characters")]
        [MinLength(4, ErrorMessage = "Channel Name must have at least 4 characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Channel Type is required")]
        [StringLength(100, ErrorMessage = "Channel Type must have at most 200 characters")]
        [MinLength(3, ErrorMessage = "Channel Type must have at least 4 characters")]
        public string Type { get; set; }

        [Required(ErrorMessage = "The workspace is mandatory")]
        public int? WorkspaceId { get; set; }

        public virtual Workspace? Workspace { get; set; }

        public ICollection<Post>? Posts { get; set; }
    }
}

Proiect_DAW-DeliANN/Controllers/PostsController.cs
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proiect_DAW_DeliANN.Data;
using Proiect_DAW_DeliANN.Models;
using System.Net.NetworkInformation;
//using System.Threading.Channels;

namespace Proiect_DAW_DeliANN.Controllers
{
    public class PostsController : Controller
    {

        //presupun ca o sa am nevoie de new/edit/delete cu mentiunea sa am grija cine are voie sa faca asta
        //o sa am lista de useri in dreapta 
        //o sa am optiune de raspuns => o sa am o metoda (un buton ig) care o sa ia id-ul si il trimite in metoda
        //si o sa apara cumva sters idk still thinking
        //ce e de mentionat e ca o sa aiba poza de profil yucky
        //anyways si reaction o sa ai un buton, o lista initial hidden si dupa apare cu ce alegi si poti sa alegi doar unul si sa il schimbi
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWebHostEnvironment _env;
        public PostsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager,
         IWebHostEnvironment env
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }
        //Delete pe post => ai voie doar ca admin/editor/tu care l-a scris/mod
        [HttpPost]
        [Authorize(Roles = "User,Editor,Admin")]    //DE SETAT ACCESSRIGHTS PE BAZA ROLULUI IN WORKSPACE (LA FEL CA IN WORKSPACE SHOW) - PENTRU CA APOI IN VIEW SA STIM CAND SAU NU AFISAM BUTOANELE DE EDIT/DELETE
        public IActionResult Delete(int id)
        {
            Post post = db.Posts
               .Include(p => p.Channel)
               .FirstOrDefault(p => p.PostId == id);
            if (post == null)
            {
                return Forbid();
            }

            //facem rost de workspace-ul in care se afla postarea
            int? workspaceId = post.Channel.WorkspaceId;

            var userId = _userManager.GetUserId(User);

            var userWorkspace = db.ApplicationUserWorkspaces //verifica daca userul e moderator in workspace
                                  .FirstOrDefault(uw => uw.UserId == userId && uw.WorkspaceId == workspaceId && uw.moderator == true);


            Console.WriteLine(userWorkspace);
            if (!User.IsInRole("Admin") && !User.IsInRole("Editor") && userWorkspace == null && post.UserId != userId) //aceeasi modificare ca la edit
            {
                //TempData["message"] = "You can't edit this post";
                //TempData["messageType"] = "alert-danger";
                return Redirect("/Channels/Show/" + post.ChannelId);
            } 
            db.Posts.Remove(post);
            db.SaveChanges();

            //TempData["message"] = "Post deleted successfully";
            //TempData["messageType"] = "alert-success";

            return Redirect("/Channels/Show/" + post.ChannelId);
        }

        [Authorize(Roles = "User,Editor,Admin")]
        public IActionResult Edit(int id)
        {
            Console.WriteLine("Vreau sa editez!");
            Post post = db.Posts
               .Include(p => p.Channel)
               .FirstOrDefault(p => p.PostId == id);
            if (post == null)
            {
                return Forbid();
            }
            Console.WriteLine(post.ChannelId);
            //facem rost de workspace-ul in care se afla postarea
            int? workspaceId = post.Channel.WorkspaceId;
            Console.WriteLine(workspaceId);
            var userId = _userManager.GetUserId(User);

            var userWorkspace = db.ApplicationUserWorkspaces //verifica daca userul e moderator in workspace
                                  .FirstOrDefault(uw => uw.UserId == userId && uw.WorkspaceId == workspaceId && uw.moderator == true);

            
            Console.WriteLine(userWorkspace);
            if (!User.IsInRole("Admin") && !User.IsInRole("Editor") && userWorkspace == null && post.UserId != userId) //aceeasi modificare ca la edit
            {
                    //TempData["message"] = "You can't edit this post";
                    //TempData["messageType"] = "alert-danger";
                    return Redirect("/Channels/Show/" + post.ChannelId);
            }
            return View(post);
        }

        [HttpPost]
        [Authorize(Roles = "User,Editor,Admin")]
        public IActionResult Edit(int id, Post requestPost)
        {
            Post post = db.Posts
               .Include(p => p.Channel)
               .FirstOrDefault(p => p.PostId == id);
            if (post == null)
            {
                return Forbid();
            }
    
            //facem rost de workspace-ul in care se afla postarea
            int? workspaceId = post.Channel.WorkspaceId;

            var userId = _userManager.GetUserId(User);

            var userWorkspace = db.ApplicationUserWorkspaces //verifica daca userul e moderator in workspace
                                  .FirstOrDefault(uw => uw.UserId == userId && uw.WorkspaceId == workspaceId && uw.moderator == true);


            Console.WriteLine(userWorkspace);
            if (!User.IsInRole("Admin") && !User.IsInRole("Editor") && userWorkspace == null && post.UserId != userId) //aceeasi modificare ca la edit
            {
                //TempData["message"] = "You can't edit this post";
                //TempData["messageType"] = "alert-danger";
                return Forbid();
            }

            if (ModelState.IsValid)
            {
                if (requestPost.ChannelId != post.ChannelId)
                {
                    return View(requestPost); //ne intoarcem in formular
                }
                Console.WriteLine("Boom");
                //updatam campurile
                post.Content = requestPost.Content;
                post.Type = requestPost.Type;
                db.SaveChanges();
                Console.WriteLine("Boom");
                //TempData["message"] = "Channel updated successfully";
                //TempData["messageType"] = "alert-success";
                Console.WriteLine("Boom");
                return Redirect("/Channels/Show/" + post.ChannelId);
            }
            else
            {
                Console.WriteLine("Boom");
                return View(requestPost);
            }

        }

        [Authorize(Roles = "User,Editor,Admin")]
        public IActionResult New(int? id)
        {
            if (!User.IsInRole("Admin") && !User.IsInRole("Editor"))
            {
                var userId = _userManager.GetUserId(User);
                Channel chan = db.Channels.Find(id);
                //Channel chn = db.Channels.Include("Workspaces").Where(c => c.ChannelId == id).First();
                int? wrkId = chan.WorkspaceId;
                var userWorkspace = db.ApplicationUserWorkspaces
                                      .FirstOrDefault(uw => uw.WorkspaceId == wrkId && uw.UserId == userId); //verificam daca e moderator in acest workspace


                if (userWorkspace == null)
                { //acest user nu are drept sa creeze canale pe acest worksop
                    TempData["message"] = "You can't add a new post in this channel.";
                    TempData["messageType"] = "alert-danger";
                    return Redirect("/Workspaces/Index/");
                }
            }
            if (id != null) //s-a intrat legal pe aceasta metoda :)))))((*9
            {
                //creare canal nou
                Post post = new Post //MOTIV PENTRU CARE CRAPA NEW-UL (nu primea workspaceId desi noi il setam aici):
                {                             //chiar daca noi il completam de aici pt canalul ce va fi nou, este nevoie ca in form-ul din view sa avem si input hidden pt acest camp ca sa realizez model binding
                    ChannelId = id,
                    UserId = _userManager.GetUserId(User)
                };

                return View(post); //mergem in view pentru a completa restul campurilor
            }
            else //cazul de intrare prin Channels/New direct (fara workspaceId)
            {
                return Forbid();
            }
        }

        [HttpPost]
        [Authorize(Roles = "User,Editor,Admin")]
        public async Task<IActionResult> New(Post post, IFormFile Media) //de reparat new-ul astfel incat sa putem incarca postare si fara continut media
        {
            var sanitizer = new HtmlSanitizer();


            if (!User.IsInRole("Admin") && !User.IsInRole("Editor"))
            {

                var userId = _userManager.GetUserId(User);

                var userWorkspace = db.ApplicationUserWorkspaces
                                      .FirstOrDefault(uw => uw.UserId == userId);

                if (userWorkspace == null)
                {
                    return Forbid();
                }


            }


            post.Date = DateTime.Now;
            post.UserId = _userManager.GetUserId(User);
            Console.WriteLine("test media2");
            if (Media != null && Media.Length > 0)
            {
                Console.WriteLine("test media3");
                //Verificam extensia
                var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif", ".mp4", ".mov" };
                var fileExtension = Path.GetExtension(Media.FileName).ToLower();
                if (!allowedExtensions.Contains(fileExtension))
                {
                    ModelState.AddModelError("PostMedia", "Wrong format :jpg, jpeg, png, gif, mp4, mov only.");
                    return View(post);
                }
                // Cale stocare

Proiect_DAW-DeliANN/Controllers/ProfilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Proiect_DAW_DeliANN.Data;
using Proiect_DAW_DeliANN.Models;

namespace Proiect_DAW_DeliANN.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWebHostEnvironment _env; //ne trebuie pt poza de profil

        public ProfilesController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
              IWebHostEnvironment env) //se adauga si in constructor
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }

        public IActionResult Show(string id)
        {
            Profile profile = db.Profiles
                                .Include(p => p.User)
                                .FirstOrDefault(p => p.UserId == id); //nu cautam dupa cheia primara deci trebuie cu FirstOrDeafult. Altfel mergea si cu Find
            if (profile == null)
            {
                return NotFound();
            }

            ViewBag.Status = profile.IsActive switch //switch pt a afisa statusul userului
            {
                true => "Active",
                false => "Inactive",
                null => "Hidden"
            };

            SetAccessRights(id); //stabilim privilegiile (pentru butonul de edit profile din Show)

            if (TempData.ContainsKey("message")) //verificam daca e vreun mesaj de afisat
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            return View(profile);
        }

        [Authorize(Roles ="Admin,Editor,User")]
        public IActionResult Edit(int id)
        {
            Profile profile = db.Profiles.Find(id);

            if (profile == null)
            {
                return NotFound();
            }

            if((profile.UserId == _userManager.GetUserId(User)) || //ne asiguram ca este profilul userului curent pt a avea dreptul sa-l editeze
                    User.IsInRole("Admin") || User.IsInRole("Editor"))
            {
                return View(profile);
            }
            else
            {
                TempData["message"] = "You don't have the right to modify this profile!";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Show", new { id = profile.UserId }); //nu ie voie
            }
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin")]
        public async Task<IActionResult> Edit(int id, Profile requestProfile, IFormFile? Image)
        {
            Profile profile = db.Profiles.Find(id);
            if(ModelState.IsValid)
            {
                if ((profile.UserId == _userManager.GetUserId(User)) //verificam iar ca userul poate efectua editul
                    || User.IsInRole("Admin") || User.IsInRole("Editor"))
                {
                    profile.Bio = requestProfile.Bio;
                    profile.DisplayName = requestProfile.DisplayName;
                    profile.IsActive = requestProfile.IsActive;

                    //partea cu imaginea
                    if (Image != null && Image.Length > 0)
                    {
                        Console.WriteLine("Debug4");
                        var allowedExtensions = new[] { ".jpg", ".jpeg", ".png" }; //Pentru profil il lasam doar sa aiba poza!! nu punem si extentii de tip mp4 sau mov etc. Alea sunt pt postari

                        var fileExtension = Path.GetExtension(Image.FileName).ToLower();

                        if (!allowedExtensions.Contains(fileExtension))
                        {
                            Console.WriteLine("Debug5");
                            ModelState.AddModelError("ProfileImage", "The file needs to be a jpg, jpeg or png.");
                            return View(profile);
                        }

                        var storagePath = Path.Combine(_env.WebRootPath, "images", Image.FileName);
                        var databaseFileName = "/images/" + Image.FileName;
                        using (var fileStream = new FileStream(storagePath, FileMode.Create))
                        {
                            await Image.CopyToAsync(fileStream);
                        }

                        Console.WriteLine("Debug6");
                        ModelState.Remove(nameof(profile.ProfileImage));
                        profile.ProfileImage = databaseFileName;
                    }

                    //profilul a fost editat cu succes
                    TempData["message"] = "Profile updated successfully!";
                    TempData["messageType"] = "alert-success";
                    db.SaveChanges();
                    return RedirectToAction("Show", new {id=profile.UserId});
                }

                else
                {
                    Console.WriteLine("Debug8");
                    TempData["message"] = "You don't have the right to modify this profile!";
                    TempData["messageType"] = "alert-danger";
                    return RedirectToAction("Show", new { id = profile.UserId }); //nu ie voie
                }
            }
            else
            {
                Console.WriteLine("Debug9");
                return View(requestProfile); //inapoi la editare
            }
        }

        private void SetAccessRights(string UserId)
        {
            ViewBag.EsteAdmin = User.IsInRole("Admin");
            ViewBag.EsteEditor = User.IsInRole("Editor");

            var currentUserId = _userManager.GetUserId(User);

            ViewBag.OwnProfile = currentUserId == UserId; //variabila in care retinem daca userul curent este si detinatorul profilului
        }
    }
}

Proiect_DAW-DeliANN/Views/Channels/Edit.cshtml
@model Proiect_DAW_DeliANN.Models.Channel

@{
    // Definim culorile
    var primaryColor = "#BE95BE";
    var secondaryColor = "#9B629B";
    var accentColor = "#813D81";
    var darkAccentColor = "#692369";
    var deepDarkColor = "#4D0C4D";
}

<!-- Injectam variabilele css in pagina -->
<style>
    :root {
        --primary-color: @primaryColor;
        --secondary-color: @secondaryColor;
        --accent-color: @accentColor;
        --dark-accent-color: @darkAccentColor;
        --deep-dark-color: @deepDarkColor;
    }
</style>

<link href="~/css/FormStylings.css" rel="stylesheet" />

<h2 class="text-center mt-5">Channel Editing</h2>

<div class="container mt-5">
    <div class="row">
        <div class="col-6 offset-3">

            <form method="post" asp-action="Edit" asp-controller="Channels" asp-route-id="@Model.ChannelId">

                <div asp-validation-summary="All" class="text-danger"></div>

                <input type="hidden" asp-for="WorkspaceId" /> @*campul ascuns prin care trimitem si WorkspaceId spre model binding*@

                <div class="form-group">
                    <label asp-for="Name" class="form-label">Channel Name</label>
                    <br />
                    <input asp-for="Name" class="form-control custom-input" />

                    <!-- Mesaj de validare pentru nume canal -->
                    <span asp-validation-for="Name" class="text-danger"></span>

                    <br /><br />
                </div>

                <div class="form-group">
                    <label asp-for="Type" class="form-label">Channel Type</label>
                    <br />
                    <textarea asp-for="Type" class="form-control summernote custom-textarea"></textarea>

                    <!-- Mesaj de validare pentru tip canal -->
                    <span asp-validation-for="Type" class="text-danger"></span>

                    <br /><br />
                </div>

                <br />
                <button class="btn btn-success custom-btn" type="submit">Save</button>

            </form>
        </div>
    </div>
</div>

Proiect_DAW-DeliANN/Views/Channels/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Proiect_DAW-DeliANN/Views/Channels/New.cshtml
@model Proiect_DAW_DeliANN.Models.Channel

@{
    // Definim culorile
    var primaryColor = "#BE95BE";
    var secondaryColor = "#9B629B";
    var accentColor = "#813D81";
    var darkAccentColor = "#692369";
    var deepDarkColor = "#4D0C4D";
}

<!-- Injectam variabilele css in pagina -->
<style>
    :root {
        --primary-color: @primaryColor;
        --secondary-color: @secondaryColor;
        --accent-color: @accentColor;
        --dark-accent-color: @darkAccentColor;
        --deep-dark-color: @deepDarkColor;
    }
</style>

<link href="~/css/FormStylings.css" rel="stylesheet" />

<h2 class="text-center mt-5">Add Channel</h2>

<div class="container mt-5">
    <div class="row">
        <div class="col-6 offset-3">

            <form method="post" asp-action="New" asp-controller="Channels">

                <div asp-validation-summary="All" class="text-danger"></div>

                <input type="hidden" asp-for="WorkspaceId" /> @*campul ascuns prin care trimitem si WorkspaceId spre model binding*@

                <div class="form-group">
                    <label asp-for="Name" class="form-label">Channel Name</label>
                    <br />
                    <input asp-for="Name" class="form-control custom-input" />

                    <!-- Mesaj de validare pentru nume canal -->
                    <span asp-validation-for="Name" class="text-danger"></span>

                    <br /><br />
                </div>

                <div class="form-group">
                    <label asp-for="Type" class="form-label">Channel Type</label>
                    <br />
                    <textarea asp-for="Type" class="form-control summernote custom-textarea"></textarea>

                    <!-- Mesaj de validare pentru tip canal -->
                    <span asp-validation-for="Type" class="text-danger"></span>

                    <br /><br />
                </div>

                <br />
                <button class="btn btn-success custom-btn" type="submit">Add</button>

            </form>
        </div>
    </div>
</div>

Proiect_DAW-DeliANN/Views/Channels/Show.cshtml
@model Proiect_DAW_DeliANN.Models.Channel

@{
    // Definim culorile
    var primaryColor = "#BE95BE";
    var secondaryColor = "#9B629B";
    var accentColor = "#813D81";
    var darkAccentColor = "#692369";
    var deepDarkColor = "#4D0C4D";
}

<!-- Injectam variabilele css in pagina -->
<style>
    :root {
        --primary-color: @primaryColor;
        --secondary-color: @secondaryColor;
        --accent-color: @accentColor;
        --dark-accent-color: @darkAccentColor;
        --deep-dark-color: @deepDarkColor;
    }
</style>

<link href="~/css/ChannelStyle.css" rel="stylesheet" />

<div class="card">

    <div class="card-body">


        <div class="intro-channel">

            <h3 class="card-title alert-success py-3 px-3 rounded-2">@Model.Name</h3>

            <div><i class="bi bi-globe"></i> @Model.Type</div>


        </div>

    </div>


</div>

<br />
<div class="container mt-3">
    <div class="d-flex flex-row justify-content-between">

        <div class="col-md-3 d-flex culoare">
            <div class="bg-light p-3 rounded channels-div">
                <h5>Channels</h5>
                <ul class="list-unstyled">
                    @foreach (var chn in ViewBag.WorkspaceChannels)
                    {
                        <li class="mb-2">
                            <a class="btn btn-channel" asp-controller="Channels" asp-action="Show" asp-route-id="@chn.ChannelId">@chn.Name</a>
                        </li>
                    }
                </ul>
            </div>
        </div>


        <div class="col-md-6">
            <div class="scrollable">
                @foreach (var post in Model.Posts)
                {
                    <div class="container mb-4 p-3 border rounded add-margin">
                        <div class="d-flex flex-row justify-content-between">
                            <a asp-controller="Profiles" asp-action="Show" asp-route-id="@post.User.Profile.UserId" class="d-flex align-items-center text-decoration-none">
                                <img src="@post.User.Profile.ProfileImage" alt="Profile Picture" class="rounded-circle me-3" style="width: 30px; height: 30px;" />
                                <span class="display-username">
                                    <strong>@post.User.Profile.DisplayName</strong>
                                </span>
                            </a>

                            <small class="text-muted post-date">@post.Date</small>
                        </div>


                        <div class="d-flex flex-row justify-content-around align-items-center">
                            <p>@post.Content</p>
                            @*@if (@post.Media != null)
                        {
                        <img src="@post.Media" alt="Media" class="img-thumbnail" style="width:150px; height:150px;" />
                        }*@
                            @if (@post.Media != null)
                            {
                                string extension = (post.Media).Split(".")[1].ToLower();


                                @if (new[] { "jpg", "jpeg", "png", "gif" }.Contains(extension))
                                {
                                    <img src="@post.Media" alt="Media" class="img-thumbnail" style="width:150px; height:150px;" />
                                }
                                else if (extension == "mp4")
                                {
                                    <video controls style="max-width:560;">
                                        <source src="@post.Media" type="video/mp4" />
                                    </video>
                                }
                                else
                                {
                                    <video controls style="max-width:560;">
                                        <source src="@post.Media" />
                                    </video>
                                }
                            }
                        </div>

                     
                        @*@foreach (var user in ViewBag.Users)
                    {
                    @if @post.User.UserId
                    }*@

                        @if (ViewBag.AfisareButoane == true || post.UserId == ViewBag.UserCurent)
                        {

                            <div class="d-flex flex-row justify-content-center align-items-center post-btns">
                                <!-- Edit Button -->
                                <a asp-controller="Posts" asp-action="Edit" asp-route-id="@post.PostId" class="btn edit-btn">
                                    <i class="bi bi-pencil"></i> Edit
                                </a>

                                <!-- Delete Button -->
                                <form asp-action="Delete" asp-controller="Posts" asp-route-id=" @post.PostId" method="post">
                                    <button type="submit" class="btn delete-btn">
                                        <i class="bi bi-trash"></i> Delete
                                    </button>
                                </form>

                                @*<a href="#reply-form" asp-action="Show" asp-controller="Channels"
                        class="btn btn-info btn-sm ms-2" data-parent-id="@post.PostId">
                        <i class="bi bi-reply"></i> Reply
                        </a>*@

                                <!-- Reply Form for the current post -->

                            </div>
                        }
                    </div>
                }

            </div>
            <a class="btn add-btn w-100" asp-area="" asp-controller="Posts" asp-action="New" asp-route-id="@Model.ChannelId">Add a post!</a>
        </div>

        @*Afisare lista useri*@
        <div class="d-flex flex-column justify-content-start">
            <h4 class="section-title text-center">Members:</h4>

            <div class="users-container">
                @if (ViewBag.Users != null && ViewBag.Users.Count > 0)
                {
                    <ul class="list-group">
                        @foreach (var user in ViewBag.Users)
                        {
                            <li class="list-group-item d-flex align-items-center">
                                @*orice user poate vizualiza ceilalti useri*@
                                <a asp-controller="Profiles" asp-action="Show" asp-route-id="@user.UserId" class="d-flex align-items-center text-decoration-none">
                                    <img src="@user.ProfileImage" alt="Profile Picture" class="rounded-circle me-3" style="width: 50px; height: 50px;" />
                                    <span class="display-username">
                                        <strong>@user.DisplayName</strong>
                                    </span>
                                </a>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <p>No current members.</p>
                }
            </div>
        </div>

    </div>
   
</div>