Proiect_DAW-DeliANN/Models/Workspace.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Proiect_DAW_DeliANN.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static Proiect_DAW_DeliANN.Models.ApplicationUserWorkspaces;

namespace Proiect_DAW_DeliANN.Models
{
    public class Workspace
    {
        [Key]
        public int WorkspaceId { get; set; }

        [Required(ErrorMessage = "Workspace Name is required")]
        [StringLength(200, ErrorMessage = "Workspace Name must have at most 200 characters")]
        [MinLength(4, ErrorMessage = "Workspace Name must have at least 4 characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Workspace Description is required")]
        public string Description { get; set; }

        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Workspace must have a Category!")]
        public int? CategoryId { get; set; }

        public string? UserId { get; set; }

        public virtual Category? Category { get; set; }

        public virtual ApplicationUser? User { get; set; }
        public ICollection<Channel>? Channels { get; set; }

        public virtual ICollection<ApplicationUserWorkspace>? ApplicationUserWorkspaces { get; set; }

        [NotMapped]
        public IEnumerable<SelectListItem>? Categ { get; set; }
    }
}

Proiect_DAW-DeliANN/Controllers/ProfilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Proiect_DAW_DeliANN.Data;
using Proiect_DAW_DeliANN.Models;

namespace Proiect_DAW_DeliANN.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWebHostEnvironment _env; //ne trebuie pt poza de profil

        public ProfilesController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
              IWebHostEnvironment env) //se adauga si in constructor
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }

        public IActionResult Show(string id)
        {
            Profile profile = db.Profiles
                                .Include(p => p.User)
                                .FirstOrDefault(p => p.UserId == id); //nu cautam dupa cheia primara deci trebuie cu FirstOrDeafult. Altfel mergea si cu Find
            if (profile == null)
            {
                return NotFound();
            }

            ViewBag.Status = profile.IsActive switch //switch pt a afisa statusul userului
            {
                true => "Active",
                false => "Inactive",
                null => "Hidden"
            };

            SetAccessRights(id); //stabilim privilegiile (pentru butonul de edit profile din Show)

            if (TempData.ContainsKey("message")) //verificam daca e vreun mesaj de afisat
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            return View(profile);
        }

        [Authorize(Roles ="Admin,Editor,User")]
        public IActionResult Edit(int id)
        {
            Profile profile = db.Profiles.Find(id);

            if (profile == null)
            {
                return NotFound();
            }

            if((profile.UserId == _userManager.GetUserId(User)) || //ne asiguram ca este profilul userului curent pt a avea dreptul sa-l editeze
                    User.IsInRole("Admin") || User.IsInRole("Editor"))
            {
                return View(profile);
            }
            else
            {
                TempData["message"] = "You don't have the right to modify this profile!";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Show", new { id = profile.UserId }); //nu ie voie
            }
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin")]
        public async Task<IActionResult> Edit(int id, Profile requestProfile, IFormFile? Image)
        {
            Profile profile = db.Profiles.Find(id);
            if(ModelState.IsValid)
            {
                if ((profile.UserId == _userManager.GetUserId(User)) //verificam iar ca userul poate efectua editul
                    || User.IsInRole("Admin") || User.IsInRole("Editor"))
                {
                    profile.Bio = requestProfile.Bio;
                    profile.DisplayName = requestProfile.DisplayName;
                    profile.IsActive = requestProfile.IsActive;

                    //partea cu imaginea
                    if (Image != null && Image.Length > 0)
                    {
                        Console.WriteLine("Debug4");
                        var allowedExtensions = new[] { ".jpg", ".jpeg", ".png" }; //Pentru profil il lasam doar sa aiba poza!! nu punem si extentii de tip mp4 sau mov etc. Alea sunt pt postari

                        var fileExtension = Path.GetExtension(Image.FileName).ToLower();

                        if (!allowedExtensions.Contains(fileExtension))
                        {
                            Console.WriteLine("Debug5");
                            ModelState.AddModelError("ProfileImage", "The file needs to be a jpg, jpeg or png.");
                            return View(profile);
                        }

                        var storagePath = Path.Combine(_env.WebRootPath, "images", Image.FileName);
                        var databaseFileName = "/images/" + Image.FileName;
                        using (var fileStream = new FileStream(storagePath, FileMode.Create))
                        {
                            await Image.CopyToAsync(fileStream);
                        }

                        Console.WriteLine("Debug6");
                        ModelState.Remove(nameof(profile.ProfileImage));
                        profile.ProfileImage = databaseFileName;
                    }

                    //profilul a fost editat cu succes
                    TempData["message"] = "Profile updated successfully!";
                    TempData["messageType"] = "alert-success";
                    db.SaveChanges();
                    return RedirectToAction("Show", new {id=profile.UserId});
                }

                else
                {
                    Console.WriteLine("Debug8");
                    TempData["message"] = "You don't have the right to modify this profile!";
                    TempData["messageType"] = "alert-danger";
                    return RedirectToAction("Show", new { id = profile.UserId }); //nu ie voie
                }
            }
            else
            {
                Console.WriteLine("Debug9");
                return View(requestProfile); //inapoi la editare
            }
        }

        private void SetAccessRights(string UserId)
        {
            ViewBag.EsteAdmin = User.IsInRole("Admin");
            ViewBag.EsteEditor = User.IsInRole("Editor");

            var currentUserId = _userManager.GetUserId(User);

            ViewBag.OwnProfile = currentUserId == UserId; //variabila in care retinem daca userul curent este si detinatorul profilului
        }
    }
}

Proiect_DAW-DeliANN/Controllers/WorkspacesController.cs
using Proiect_DAW_DeliANN.Data;
using Proiect_DAW_DeliANN.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static Proiect_DAW_DeliANN.Models.ApplicationUserWorkspaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ganss.Xss;

namespace Proiect_DAW_DeliANN.Controllers
{
    [Authorize]
    public class WorkspacesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public WorkspacesController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager
            )
            {
                db = context;
                _userManager = userManager;
                _roleManager = roleManager;
            }

        //Afisarea tuturor Workspace-urilor impreuna cu categoria din care fac parte
        //Fiecare workspace va avea un buton de Request daca userul nu a incercat inca sa se alature
        //Daca se afla in asteptare (exista inregistrarea user_workspace in tabelul intermediar cu False), se va afisa un mesaj (Waiting for approval...)
        //Daca face parte din workspace, user-ul va putea intra sa vizualizeze continutul (Open workspace)
        [Authorize(Roles = "User,Editor,Admin")]
        public IActionResult Index()
        {
            var workspaces = db.Workspaces.Include("Category")
                             .OrderByDescending(w => w.Date);

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            //Mototul de cautare
            var search = "";
            
            //Se vor realiza cautari dupa: Numele workspace-ului, Categoria acestuia, dar si dupa descriere
            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim(); // eliminam spatiile libere 

                //Cautare in workspace (nume,categorie,descriere)
                List<int> workspaceIds = db.Workspaces.Where(
                                         w => w.Name.Contains(search)
                                         || w.Description.Contains(search)
                                         || w.Category.CategoryName.Contains(search)
                                         ).Select(a => a.WorkspaceId).ToList();

                //lista workspace-urilor care contin cuvantul cautat (intr-unul din campurile vizate)
                workspaces = db.Workspaces.Where(workspace => workspaceIds.Contains(workspace.WorkspaceId))
                                          .Include("Category")
                                          .OrderByDescending(w => w.Date);
            }

            ViewBag.SearchString = search;

            //AFISARE PAGINATA

            //Sa zicem 4 workspace-uri pe pagina momentan
            int _perPage = 4;
            int totalItems = workspaces.Count(); //toate workspace-urile

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta
            // /Workspaces/Index?page=valoare

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 4 =>  Asadar offsetul este egal cu numarul de workspace-uri care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            //Preluarea workspace-uri corespunzatoare pentru fiecare pagina la care ne aflam in functie de offset
            var paginatedWorkspaces = workspaces.Skip(offset).Take(_perPage);

            //Numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);
            //Trimitere workspace-uri catre View-ul corespunzator
            ViewBag.Workspaces = paginatedWorkspaces;

            //DACA AVEM AFISAREA PAGINATA IMPREUNA CU SEARCH
            if(search != "")
            {
                ViewBag.PaginationBaseUrl = "/Workspaces/Index/?search=" + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/Workspaces/Index/?page";
            }

            var userId = _userManager.GetUserId(User); //trimitem in viewbag id-ul userului curent si toate campurile WorkSpaceId si status din tabelul asociativ
            var userWorkspaceRelations = db.ApplicationUserWorkspaces //daca trimiteam tot tabelul nu mergea in view sa accesez campurile for some reason
                                         .Where(uw => uw.UserId == userId)
                                         .Select (uw => new {uw.WorkspaceId, uw.status})
                                         .ToList();

            ViewBag.UserWorkspaceRelations = userWorkspaceRelations;

            SetUserWorkspaceStatus(); //functie care identifica toate perspectivele posibile pe care un user le poatea avea fata de un workspace
                                      //pe baza acestei perspective se vor afisa butoane/mesaje corespunzatoare pentru user

            return View();
        }


        [Authorize(Roles = "User")] //Afisarea tuturor workspace-urilor din care userul face parte sau pentru care este in asteptare
        public IActionResult Index_personalizat_user()
        {
            var userId = _userManager.GetUserId(User); //id-ul userului curent

            var filteredWorkspaces = db.Workspaces.Include("Category") //selectam doar workspace-urile in care exista o legatura in tabelul asociativ intr user si acesta
                                                  .Where(w => db.ApplicationUserWorkspaces
                                                            .Any(uw => uw.WorkspaceId == w.WorkspaceId && uw.UserId == userId))
                                                  .OrderByDescending(w => w.Date);

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            //Mototul de cautare
            var search = "";

            //Se vor realiza cautari dupa: Numele workspace-ului, Categoria acestuia, dar si dupa descriere
            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim(); // eliminam spatiile libere 

                //Cautare in workspace (nume,categorie,descriere)
                List<int> workspaceIds = db.Workspaces.Where(
                                         w => w.Name.Contains(search)
                                         || w.Description.Contains(search)
                                         || w.Category.CategoryName.Contains(search)
                                         ).Select(a => a.WorkspaceId).ToList();

                //lista workspace-urilor care contin cuvantul cautat (intr-unul din campurile vizate)
                filteredWorkspaces = db.Workspaces.Where(workspace => workspaceIds.Contains(workspace.WorkspaceId))
                                          .Include("Category")
                                          .Where(w => db.ApplicationUserWorkspaces
                                                            .Any(uw => uw.WorkspaceId == w.WorkspaceId && uw.UserId == userId))
                                          .OrderByDescending(w => w.Date);
            }

            ViewBag.SearchString = search;

            //AFISARE PAGINATA

            //Sa zicem 4 workspace-uri pe pagina momentan
            int _perPage = 4;
            int totalItems = filteredWorkspaces.Count(); //toate workspace-urile

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta
            // /Workspaces/Index?page=valoare

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 4 =>  Asadar offsetul este egal cu numarul de workspace-uri care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            //Preluarea workspace-uri corespunzatoare pentru fiecare pagina la care ne aflam in functie de offset
            var paginatedWorkspaces = filteredWorkspaces.Skip(offset).Take(_perPage);

            //Numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);
            //Trimitere workspace-uri catre View-ul corespunzator
            ViewBag.Workspaces = paginatedWorkspaces;

            //DACA AVEM AFISAREA PAGINATA IMPREUNA CU SEARCH
            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/Workspaces/Index_personalizat_user/?search=" + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/Workspaces/Index_personalizat_user/?page";
            }

            //trimitem in viewbag id-ul userului curent si toate campurile WorkSpaceId si status din tabelul asociativ

Proiect_DAW-DeliANN/Views/Workspaces/Show.cshtml
@model Proiect_DAW_DeliANN.Models.Workspace

@{
    // Definim culorile
    var primaryColor = "#BE95BE";
    var secondaryColor = "#9B629B";
    var accentColor = "#813D81";
    var darkAccentColor = "#692369";
    var deepDarkColor = "#4D0C4D";
}

<!-- Injectam variabilele css in pagina -->
<style>
    :root {
        --primary-color: @primaryColor;
        --secondary-color: @secondaryColor;
        --accent-color: @accentColor;
        --dark-accent-color: @darkAccentColor;
        --deep-dark-color: @deepDarkColor;
    }
</style>

<link href="~/css/WorkspaceShow2.css" rel="stylesheet" />

@if (TempData["message"] != null)
{
    <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5">
        @ViewBag.Message
    </div>
}
<br />
<div class="container">
    <div class="workspace-info-card card mb-4">
        <div class="card-body">

            <h4 class="section-title-workspace text-center mb-3">@Model.Name</h4>

            <div class="workspace-info-container mt-5">
                <div class="left-section card-text text-start">@Html.Raw(Model.Description)</div>

                <div class="right-section">

                    <div><i class="bi bi-globe"></i> @Model.Category.CategoryName</div>

                    <div><i class="bi bi-person"></i> Created by: @Model.User.Profile.DisplayName</div>

                    <p>Last edited: <span class="last-edited">@Model.Date</span> </p>

                </div>
            </div>

        </div>

        @if (ViewBag.AfisareButoane == true)
        {
            <div class="d-flex justify-content-between mt-3">

                <a class="btn btn-success safe-btn" asp-controller="Workspaces" asp-action="Edit" asp-route-id="@Model.WorkspaceId">Edit Workspace</a>

                <form method="post" asp-controller="Workspaces" asp-action="Delete" asp-route-id="@Model.WorkspaceId">

                    <button class="btn btn-danger danger-btn" type="submit">Delete workspace</button>

                </form>

                <a class="btn btn-success safe-btn" asp-controller="Workspaces" asp-action="ShowRequests" asp-route-id="@Model.WorkspaceId">See Requests</a>

            </div>
        }
    </div>

</div>

<br />
<br />

<div class="container">
    <div class="d-flex flex-row justify-content-between">
        @*Afisare channel-uri*@
        <div class="w-50 me-3">
            <h4 class="section-title text-center">Channel List:</h4>
            <div class="channel-list-container">
                <ul class="list-unstyled">
                    @if (Model.Channels.Count > 0)
                    {
                        @foreach (var chn in Model.Channels)
                        {
                            <li>
                                <div class="card mb-3">
                                    <div class="d-flex align-items-center justify-content-between p-2">
                                        <a class="btn btn-success text-truncate channel-name" asp-controller="Channels" asp-action="Show" asp-route-id="@chn.ChannelId">@chn.Name</a>
                                        @if (ViewBag.AfisareButoane == true) @*Doar Admin/Editor/Moderatorii de pe workspace pot edita si sterge canale*@
                                        {
                                            <div class="channel-buttons">
                                                <a class="btn btn-success me-2 channel-edit" asp-controller="Channels" asp-action="Edit" asp-route-id="@chn.ChannelId"><i class="bi bi-pencil-square"></i> Edit </a>
                                                <form method="post" asp-controller="Channels" asp-action="Delete" asp-route-id="@chn.ChannelId">

                                                    <button class="btn btn-danger channel-delete" type="submit"><i class="bi bi-trash-fill"></i> Delete </button>

                                                </form>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </li>
                            <br />
                        }
                    }
                    else
                    {
                        <p>No channels have been created yet.</p>
                    }
                </ul>
            </div>
        </div>

        @*Sectiunea de useri workspace*@
        <div class="w-50">
            @*Afisare lista moderatori*@
            <h4 class="section-title text-center">Moderators in this Workspace:</h4>

            <div class="moderators-container">
                @if (ViewBag.Moderators != null && ViewBag.Moderators.Count > 0)
                {
                    <ul class="list-group">
                        @foreach (var mod in ViewBag.Moderators)
                        {
                            <li class="list-group-item d-flex align-items-center">
                                @*orice user poate vizualiza ceilalti useri*@
                                <a asp-controller="Profiles" asp-action="Show" asp-route-id="@mod.UserId" class="d-flex align-items-center text-decoration-none">
                                    <img src="@mod.ProfileImage" alt="Profile Picture" class="rounded-circle me-3" style="width: 50px; height: 50px;" />
                                    <span class="display-username">
                                        <strong>@mod.DisplayName</strong>
                                    </span>
                                </a>

                                <div class="moderator-buttons ms-auto d-flex justify-content-evenly w-50">

                                    @if (ViewBag.AfisareButoane == true) @*Avand in vedere ca aici sunt moderatori, in dreptul lor va aparea butonul de demote to user*@
                                    {
                                        @if (mod.DisplayName != "admin@test.com" && mod.DisplayName != "editor@test.com") @*un mod foarte lenes de a verifica ca mod-ul actual este chiar Admin sau Editor (basically unul din ei a creat workspace-ul)
                            in dreptul lor nu are logica sa afisam butoanele de demote/remove pt ca ei oricum o sa aiba acces la workspace si toate privilegiile in continuare*@
                                        {
                                            @*butonul de demote la nivelul de user*@
                                            <form asp-controller="Workspaces" asp-action="DemoteToUser" method="post">
                                                <input type="hidden" name="WorkspaceId" value="@mod.WorkspaceId" />
                                                <input type="hidden" name="UserId" value="@mod.UserId" />
                                                <button class="btn btn-warning demote-btn" type="submit">Demote</button> @*Mergem spre functia din controller care face campul de moderator=false*@
                                            </form>

                                            <form asp-controller="Workspaces" asp-action="RemoveMember" method="post">
                                                @*in dreptul fiecarui user va fi un buton de remove :(*@
                                                <input type="hidden" name="WorkspaceId" value="@mod.WorkspaceId" />
                                                <input type="hidden" name="UserId" value="@mod.UserId" />
                                                <button class="btn btn-danger remove-btn" type="submit">Remove</button> @*Mergem spre functia din controller ce da remove la legatura user-workspace*@
                                            </form>
                                        }
                                    }

                                </div>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <p>No moderators are currently part of this workspace.</p>
                }
            </div>

            <br />
            <br />

            @*Afisare lista useri*@
            <h4 class="section-title text-center">Users in this Workspace:</h4>

            <div class="users-container">
                @if (ViewBag.Users != null && ViewBag.Users.Count > 0)
                {
                    <ul class="list-group">
                        @foreach (var user in ViewBag.Users)
                        {
                            <li class="list-group-item d-flex align-items-center">
                                @*orice user poate vizualiza ceilalti useri*@
                                <a asp-controller="Profiles" asp-action="Show" asp-route-id="@user.UserId" class="d-flex align-items-center text-decoration-none">
                                    <img src="@user.ProfileImage" alt="Profile Picture" class="rounded-circle me-3" style="width: 50px; height: 50px;" />
                                    <span class="display-username">
                                        <strong>@user.DisplayName</strong>
                                    </span>
                                </a>
                                <div class="user-buttons ms-auto d-flex justify-content-evenly w-50" >

                                    @if (ViewBag.AfisareButoane == true) @*Avand in vedere ca aici sunt useri normal, in dreptul lor va aparea butonul de promote to moderator*@
                                    {
                                        @*butonul de promote*@
                                        <form asp-controller="Workspaces" asp-action="PromoteToMod" method="post">
                                            <input type="hidden" name="WorkspaceId" value="@user.WorkspaceId" />
                                            <input type="hidden" name="UserId" value="@user.UserId" />
                                            <button class="btn btn-success promote-btn" type="submit">Promote</button> @*Mergem spre functia din controller care face campul de moderator=true*@
                                        </form>

                                        <form asp-controller="Workspaces" asp-action="RemoveMember" method="post">
                                            @*in dreptul fiecarui user va fi un buton de remove :(*@
                                            <input type="hidden" name="WorkspaceId" value="@user.WorkspaceId" />
                                            <input type="hidden" name="UserId" value="@user.UserId" />
                                            <button class="btn btn-danger remove-btn" type="submit">Remove</button> @*Mergem spre functia din controller ce da remove la legatura user-workspace*@
                                        </form>
                                    }

                                </div>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <p>No users are currently part of this workspace.</p>
                }
            </div>

        </div>

    </div>
</div>

@if (ViewBag.AfisareButoane == true) @*Doar Admin/Editor/Moderatorii de pe workspace pot adauga canal*@
{
    <a class="btn btn-success channel-add" asp-controller="Channels" asp-action="New" asp-route-id="@Model.WorkspaceId">Add a new channel!</a>
}

@*
<div class="container">
    <div class="d-flex flex-row justify-content-between">
    <h4 class="card-title alert-success py-3 px-3 rounded-2">Users in this workspace:</h4>
    </div>
    <ul>
        @foreach (var chn in ViewBag.Users)
        {
            <li>
                <div class="card">
                <div class="d-flex flex-row justify-content-between">
                    <li>@chn.FirstName<li>
                </div>
                </div>
            </li>
            <br/>
        }
    </ul>
</div>
*@