Proiect_DAW-DeliANN/Controllers/CategoriesController.cs
using Proiect_DAW_DeliANN.Data;
using Proiect_DAW_DeliANN.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Proiect_DAW_DeliANN.Controllers
{
    [Authorize(Roles = "Admin")] //admin only
    public class CategoriesController : Controller
    {
        //PASUL 10: useri si roluri
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public CategoriesController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index() //la cezara e de tip ActionResult dar din ce inteleg e doar o forma default de IActionResult
        {
            //adaugarea in ViewBag al unui mesaj pentru afisare, daca avem ceva de transmis (adaugare/modificare/stergere categorie)
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            var categories = from category in db.Categories
                             orderby category.CategoryName
                             select category;
            ViewBag.Categories = categories; //mergem cu toate categoriile in view-ul de afisare
            return View();
        }

        public IActionResult Show(int id)
        {
            Category category = db.Categories.Find(id); //mergem in view cu categoria specificata
            return View(category);
        }

        public IActionResult New() //HTTPGET implicit
        {
            return View();
        }

        [HttpPost]
        public IActionResult New(Category cat)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(cat);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost adaugata";
                return RedirectToAction("Index");
            }
            else
            {
                return View(cat);
            }
        }

        public IActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(int id, Category requestCategory)
        {
            Category category = db.Categories.Find(id);

            if (ModelState.IsValid)
            {
                category.CategoryName = requestCategory.CategoryName;
                db.SaveChanges();
                TempData["message"] = "Categoria a fost modificata!";
                return RedirectToAction("Index");
            }
            else
            {
                return View(requestCategory);
            }
        }

        [HttpPost]
        public IActionResult Delete(int id) {
            Category category = db.Categories.Include("Workspaces")
                                             .Include("Workspaces.Channels")
                                             .Include("Workspaces.Channels.Posts")
                                             .Include("Workspaces.Channels.Posts.Reactions")
                                             .Where(c => c.CategoryId == id)
                                             .First();
            db.Categories.Remove(category);

            TempData["message"] = "Categoria a fost stearsa";
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Proiect_DAW-DeliANN/Controllers/UsersController.cs
using Proiect_DAW_DeliANN.Data;
using Proiect_DAW_DeliANN.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ArticlesApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager
            )
        {
            db = context;

            _userManager = userManager;

            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var users = from user in db.Users
                        orderby user.UserName
                        select user;

            ViewBag.UsersList = users;

            return View();
        }

        public async Task<ActionResult> Show(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            var roles = await _userManager.GetRolesAsync(user);

            ViewBag.Roles = roles;

            ViewBag.UserCurent = await _userManager.GetUserAsync(User);

            return View(user);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ApplicationUser user = db.Users.Find(id);

            ViewBag.AllRoles = GetAllRoles();

            var roleNames = await _userManager.GetRolesAsync(user); // Lista de nume de roluri

            // Cautam ID-ul rolului in baza de date
            ViewBag.UserRole = _roleManager.Roles
                                              .Where(r => roleNames.Contains(r.Name))
                                              .Select(r => r.Id)
                                              .First(); // Selectam 1 singur rol

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string id, ApplicationUser newData, [FromForm] string newRole)
        {
            ApplicationUser user = db.Users.Find(id);

            user.AllRoles = GetAllRoles();


            if (ModelState.IsValid)
            {
                user.UserName = newData.UserName;
                user.Email = newData.Email;
                user.FirstName = newData.FirstName;
                user.LastName = newData.LastName;
                user.PhoneNumber = newData.PhoneNumber;


                // Cautam toate rolurile din baza de date
                var roles = db.Roles.ToList();

                foreach (var role in roles)
                {
                    // Scoatem userul din rolurile anterioare
                    await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                // Adaugam noul rol selectat
                var roleName = await _roleManager.FindByIdAsync(newRole);
                await _userManager.AddToRoleAsync(user, roleName.ToString());

                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Delete(string id) //Trebuie modificata logica de stergere
        {
            var user = db.Users
                         .Include("ApplicationUserWorkspaces")
                         .Include("Posts")
                         .Include("Reactions")
                         .Include("Profile")
                         .Where(u => u.Id == id)
                         .First();

            //  Stergere reactii user din baza de date
            if (user.Reactions.Count > 0)
            {
                foreach (var reaction in user.Reactions)
                {
                    db.Reactions.Remove(reaction);
                }
            }

            // Stergere postari user
            if (user.Posts.Count > 0)
            {
                foreach (var post in user.Posts)
                {
                    db.Posts.Remove(post);
                }
            }

            // Stergere user din workspace-urile din care face parte (inserarile din tabelul intermediar ApplicationUserWorkspaces)
            //!! Sa nu uitam sa tratam cazul in care un workspace ramane fara singurul moderator
            if (user.ApplicationUserWorkspaces.Count > 0)
            {
                foreach (var user_workspace in user.ApplicationUserWorkspaces)
                {
                    db.ApplicationUserWorkspaces.Remove(user_workspace);
                }
            }

            db.Profiles.Remove(user.Profile); //remove la profil

            var userCreatedWorkspaces = db.Workspaces //trebuie sterse si workspace-urile create de user-ul ce va fi sters (altfel eroare null FK)
                                            .Where(w => w.UserId == id)
                                            .ToList();

            if (userCreatedWorkspaces.Count > 0) { //remove la workspace-urile create de user
                foreach (var workspace in userCreatedWorkspaces) { 
                    db.Workspaces.Remove(workspace);
                }
            }

            db.ApplicationUsers.Remove(user);

            db.SaveChanges();

            return RedirectToAction("Index");
        }


        [NonAction]
        public IEnumerable<SelectListItem> GetAllRoles()
        {
            var selectList = new List<SelectListItem>();

            var roles = from role in db.Roles
                        select role;

            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role.Id.ToString(),
                    Text = role.Name.ToString()
                });
            }
            return selectList;
        }
    }
}

Proiect_DAW-DeliANN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proiect_DAW_DeliANN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proiect_DAW_DeliANN.styles.css" asp-append-version="true" />
    @{
        // Definim culorile
        var primaryColor = "#BE95BE";
        var secondaryColor = "#9B629B";
        var accentColor = "#813D81";
        var darkAccentColor = "#692369";
        var deepDarkColor = "#4D0C4D";
    }

    <!-- Injectam variabilele css in pagina -->
    <style>
        :root {
            --primary-color: @primaryColor;
            --secondary-color: @secondaryColor;
            --accent-color: @accentColor;
            --dark-accent-color: @darkAccentColor;
            --deep-dark-color: @deepDarkColor;
        }
    </style>

    <link href="~/css/Shared.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proiect_DAW_DeliANN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">See Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Workspaces" asp-action="Index">See Workspaces</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Workspaces" asp-action="New">Add a New Workspace</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">See Users</a>
                            </li>
                        }

                        @if (User.IsInRole("Editor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Workspaces" asp-action="Index">See Workspaces</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Workspaces" asp-action="New">Add a New Workspace</a>
                            </li>
                        }

                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Workspaces" asp-action="Index">See Workspaces</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Workspaces" asp-action="New">Add a New Workspace</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container color: white">
            &copy; 2024 - Proiect_DAW_DeliANN - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>